# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7506649f73ee93a9ca789fd0c8572a7162d80c97e3203fe7be76c9fd5c2fed010ed6802ee6a64108d628ecc8a856836085fb27de380848d50435ee4b8baf93a

test:
  secret_key_base: c8538ceb7a0f8520d42acec43236da4c1d005917e892f77f0b526faffa7b3e2bb39ec657c378c37f134cc6ea971a7148a461caf0d27f589997374c09cc1e422f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
